#######################################################
# Stage 1: mongocli-builder (build stage only, not published)
#######################################################
FROM registry.access.redhat.com/ubi9/go-toolset:latest AS mongocli-builder
ARG MONGOCLI_VERSION=2.0.3
WORKDIR /tmp/
RUN curl -Lo mongodb-cli-mongocli-v${MONGOCLI_VERSION}.zip https://github.com/mongodb/mongodb-cli/archive/refs/tags/mongocli/v${MONGOCLI_VERSION}.zip
RUN unzip ./mongodb-cli-mongocli-v${MONGOCLI_VERSION}.zip
RUN cd ./mongodb-cli-mongocli-v${MONGOCLI_VERSION}/ && \
    CGO_ENABLED=1 GOOS=linux go build -a -tags strictfipsruntime -o /tmp/mongocli ./cmd/mongocli/

#######################################################
# Stage 2: base
#######################################################
FROM registry.access.redhat.com/ubi9/python-312:latest AS base
WORKDIR /opt/app-root/bin
USER root
RUN dnf install -y mesa-libGL skopeo && dnf clean all && rm -rf /var/cache/yum
USER 1001
RUN pip install --no-cache-dir -U "micropipenv[toml]"
RUN curl -L https://mirror.openshift.com/pub/openshift-v4/$(uname -m)/clients/ocp/stable/openshift-client-linux.tar.gz \
    -o /tmp/openshift-client-linux.tar.gz && \
    tar -xzvf /tmp/openshift-client-linux.tar.gz oc && \
   rm -f /tmp/openshift-client-linux.tar.gz

#######################################################
# Stage 3: common-builder
#######################################################
FROM base AS common-builder
USER root
RUN dnf install -y gcc-toolset-13 cmake ninja-build

#######################################################
# Stage 4: onnx-builder
#######################################################
FROM common-builder AS onnx-builder
USER root
WORKDIR /tmp
RUN source /opt/rh/gcc-toolset-13/enable && \
    git clone --recursive https://github.com/onnx/onnx.git && \
    cd onnx && \
    git checkout v1.18.0 && \
    git submodule update --init --recursive && \
    pip install -r requirements.txt && \
    export CMAKE_ARGS="-DPython3_EXECUTABLE=$(which python3.12)" && \
    pip wheel . -w /tmp/onnx_wheel

#######################################################
# Stage 5: openblas-builder
#######################################################
FROM common-builder AS openblas-builder
ARG OPENBLAS_VERSION=0.3.30
USER root
WORKDIR /root
RUN source /opt/rh/gcc-toolset-13/enable && \
    wget https://github.com/OpenMathLib/OpenBLAS/releases/download/v${OPENBLAS_VERSION}/OpenBLAS-${OPENBLAS_VERSION}.zip && \
    unzip OpenBLAS-${OPENBLAS_VERSION}.zip && cd OpenBLAS-${OPENBLAS_VERSION} && \
    make -j$(nproc) TARGET=POWER9 BINARY=64 USE_OPENMP=1 USE_THREAD=1 NUM_THREADS=120 DYNAMIC_ARCH=1 INTERFACE64=0

#######################################################
# Stage 6: pdf-builder
#######################################################
FROM registry.access.redhat.com/ubi9/python-312:latest AS pdf-builder
WORKDIR /opt/app-root/bin
USER root
COPY jupyter/utils/install_texlive.sh ./install_texlive.sh
COPY jupyter/utils/install_pandoc.sh ./install_pandoc.sh
RUN chmod +x install_texlive.sh install_pandoc.sh
RUN ./install_texlive.sh
RUN ./install_pandoc.sh

#######################################################
# Stage 7: jupyter-minimal
#######################################################
FROM base AS jupyter-minimal
ARG JUPYTER_REUSABLE_UTILS=jupyter/utils
ARG MINIMAL_SOURCE_CODE=jupyter/minimal/ubi9-python-3.12

WORKDIR /opt/app-root/bin
COPY ${JUPYTER_REUSABLE_UTILS} utils/
COPY ${MINIMAL_SOURCE_CODE}/start-notebook.sh ./
USER 0
COPY --from=pdf-builder /usr/local/texlive /usr/local/texlive
COPY --from=pdf-builder /usr/local/pandoc /usr/local/pandoc
ENV PATH="/usr/local/texlive/bin/powerpc64le-unknown-linux-gnu:/usr/local/texlive/bin/linux:/usr/local/pandoc/bin:$PATH"
USER 1001
WORKDIR /opt/app-root/src
ENTRYPOINT ["start-notebook.sh"]

#######################################################
# Stage 8: jupyter-datascience
#######################################################
FROM jupyter-minimal AS jupyter-datascience
ARG DATASCIENCE_SOURCE_CODE=jupyter/datascience/ubi9-python-3.12
ARG OPENBLAS_VERSION=0.3.30

LABEL name="odh-notebook-jupyter-datascience-ubi9-python-3.12" \
     summary="Jupyter data science notebook image for ODH notebooks" \
     description="Jupyter data science notebook image with base Python 3.12 builder image based on UBI9 for ODH notebooks" \
     io.k8s.display-name="Jupyter data science notebook image for ODH notebooks" \
     io.k8s.description="Jupyter data science notebook image with base Python 3.12 builder image based on UBI9 for ODH notebooks" \
     authoritative-source-url="https://github.com/opendatahub-io/notebooks" \
     io.openshift.build.commit.ref="main" \
     io.openshift.build.source-location="https://github.com/opendatahub-io/notebooks/tree/main/jupyter/datascience/ubi9-python-3.12" \
     io.openshift.build.image="quay.io/opendatahub/workbench-images:jupyter-datascience-ubi9-python-3.12"

WORKDIR /opt/app-root/bin
USER root
RUN dnf install -y jq unixODBC postgresql git-lfs libsndfile libxcrypt-compat && dnf clean all && rm -rf /var/cache/yum
COPY --from=mongocli-builder /tmp/mongocli /opt/app-root/bin/

ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/

RUN dnf install -y gcc-toolset-13 unixODBC unixODBC-devel
COPY --from=openblas-builder /root/OpenBLAS-${OPENBLAS_VERSION} /openblas
USER 1001
RUN --mount=type=bind,from=onnx-builder,source=/tmp/onnx_wheel/,target=/onnxwheels/,ro \
    pip install /onnxwheels/*.whl

USER root
RUN PREFIX=/usr/local make -C /openblas install && rm -rf /openblas

RUN ACCEPT_EULA=Y dnf install -y unixODBC-devel && dnf clean all && rm -rf /var/cache/yum

USER 1001
COPY ${DATASCIENCE_SOURCE_CODE}/Pipfile.lock ./
COPY ${DATASCIENCE_SOURCE_CODE}/setup-elyra.sh ${DATASCIENCE_SOURCE_CODE}/utils ./utils/

# grpc flag
ENV GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1

RUN echo "Installing softwares and packages" && \
    micropipenv install && \
    rm -f ./Pipfile.lock && \
    mkdir /opt/app-root/runtimes && \
    mkdir /opt/app-root/pipeline-runtimes && \
    rm /opt/app-root/share/jupyter/metadata/runtime-images/*.json && \
    sed -i -e "s/Python.*/$(python --version | cut -d '.' -f-2)\",/" /opt/app-root/share/jupyter/kernels/python3/kernel.json && \
    cp /opt/app-root/bin/utils/jupyter_server_config.py /opt/app-root/etc/jupyter && \
    jupyter labextension disable "@jupyterlab/apputils-extension:announcements" && \
    /opt/app-root/bin/utils/addons/apply.sh && \
    chmod -R g+w /opt/app-root/lib/python3.12/site-packages && \
    fix-permissions /opt/app-root -P

WORKDIR /opt/app-root/src
